ignore = [
    ".git/",
    ".devcontainer/",
    "dev-only/",
    ".gitignore",
    ".python-version",
    "README.md",
    "mugicha.toml",
    "uv.lock",
    ".gitattributes",
    "dist/",
]
show = []
